---
haproxy_frontend_port: 80
haproxy_backend_servers:
  - name: web1
    address: 192.168.67.128:80
  - name: web2
    address: 192.168.67.128:80
virtual_ips:
  - vip: 192.168.67.200
    priority: 
      haproxy1: 100
      haproxy2: 90
  - vip: 192.168.67.201
    priority:
      haproxy1: 90
      haproxy2: 100
