---
- name: Determine primary network interface
  shell: ip route | grep default | awk '{print $5}' | head -n1
  register: primary_interface
  changed_when: false

- name: Install Keepalived
  apt:
    name: keepalived
    state: present

- name: Create Keepalived configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart Keepalived

- name: Enable and start Keepalived
  systemd:
    name: keepalived
    enabled: yes
    state: started

- name: Add Keepalived handler
  ansible.builtin.meta: flush_handlers

